############# English navigation ##############

# main menu
[[main]]
name = "<i class='fa fa-house'></i>"
url = "/"
weight = 1

[[main]]
name = "Leadership"
weight = 2

[[main]]
parent = "Leadership"
name = "Hall Staff"
url = "/hall-staff"
weight = 1

[[main]]
parent = "Leadership"
name = "Hall Government"
url = "/hall-gov"
weight = 2

[[main]]
parent = "Leadership"
name = "Hall Commissioners"
url = "/hall-commissioners"
weight = 3

[[main]]
name = "About"
url = "/about"
weight = 3

# About Subpages - History, Location, Building
[[main]]
parent = "About"
name = "History & Transition"
url = "/history"
weight = 1

[[main]]
parent = "About"
name = "Location"
url = "/location"
weight = 3

[[main]]
parent = "About"
name = "Building Info"
url = "/building"
weight = 2

[[main]]
name = "New Crew"
url = "/incoming-students"
weight = 4

[[main]]
name = "Elements"
url = "/elements"
weight = 4

[[main]]
weight = 5
name = "Pages"

[[main]]
parent = "Pages"
name = "Blog"
url = "/blog"

[[main]]
parent = "Pages"
name = "Contact"
url = "/contact"

[[main]]
parent = "Pages"
name = "Authors"
url = "/authors"

[[main]]
parent = "Pages"
name = "Categories"
url = "/categories"

[[main]]
parent = "Pages"
name = "404 Page"
url = "/404"
