############# English navigation ##############

# main menu
[[main]]
name = "<i class='fa fa-house'></i>"
url = "/"
weight = 1

[[main]]
name = "Leadership"
weight = 2

[[main]]
parent = "Leadership"
name = "Hall Staff"
url = "/hall-staff"

[[main]]
parent = "Leadership"
name = "Hall Government"
url = "/hall-gov"

[[main]]
name = "About"
url = "/about"
weight = 3

# About Subpages - History, Location, Building
[[main]]
parent = "About"
name = "History & Transition"
url = "/history"
weight = 1

[[main]]
parent = "About"
name = "Location"
url = "/location"
weight = 3

[[main]]
parent = "About"
name = "Building Info"
url = "/building"
weight = 2

[[main]]
name = "Traditions"
url = "/traditions"
weight = 4

[[main]]
name = "New Crew"
url = "/incoming-students"
weight = 5
