############# English navigation ##############

# main menu
[[main]]
name = "<i class='fa fa-house' aria-hidden='true'></i><span class='sr-only'>Home</span>"
url = "/"
weight = 1

[[main]]
name = "Leadership"
weight = 2

[[main]]
parent = "Leadership"
name = "Hall Staff"
url = "/hall-staff"
weight = 1

[[main]]
parent = "Leadership"
name = "Hall Government"
url = "/hall-gov"
weight = 2

[[main]]
parent = "Leadership"
name = "Hall Commissioners"
url = "/hall-commissioners"
weight = 3

[[main]]
name = "About"
url = "/about"
weight = 3

# About Subpages - History, Location, Building
[[main]]
parent = "About"
name = "History & Transition"
url = "/history"
weight = 1

[[main]]
parent = "About"
name = "Location"
url = "/location"
weight = 3

[[main]]
parent = "About"
name = "Building Info"
url = "/building"
weight = 2

[[main]]
parent = "Events"
name = "Traditions"
url = "/events/traditions"
weight = 1

[[main]]
name = "Faith"
url = "/faith"
weight = 6

[[main]]
name = "Events"
url = "/events"
weight = 5

# [[main]]
# parent = "Events"
# name = "IronRA"
# url = "/events/ironra"
# weight = 3

[[main]]
parent = "Events"
name = "The Regatta"
url = "/events/regatta"
weight = 2

[[main]]
parent = "Events"
name = "Car Smash"
url = "/events/car-smash"
weight = 4

[[main]]
parent = "Events"
name = "Coyle Crunk"
url = "/events/crunk"
weight = 6

[[main]]
parent = "Events"
name = "Coyle Formal"
url = "/events/formal"
weight = 7

[[main]]
parent = "Events"
name = "Parents Weekend"
url = "/events/parents-weekend"
weight = 5


[[main]]
name = "New Crew"
url = "/incoming-students"
weight = 7
